export const RAPID_API_URL = process.env.NEXT_PUBLIC_RAPID_API_URL
export const RAPID_API_KEY = process.env.NEXT_PUBLIC_RAPID_API_KEY
export const RAPID_API_HOST = process.env.NEXT_PUBLIC_RAPID_API_HOST
export const KEYCLOAK_CLIENT_ID = process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
export const KEYCLOAK_CLIENT_SECRET = process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET
export const KEYCLOAK_URL = process.env.NEXT_PUBLIC_KEYCLOAK_URL
export const KEYCLOAK_REALM = process.env.NEXT_PUBLIC_KEYCLOAK_REALM

export const USER_PLAYLIST_STORAGE_KEY = 'user-playlist'
